### ISSUE TITLE
Issue With Documentation

### ISSUE THREAD

**Issue by ZombieNW** [levlups/Galactica-Source#1]
There is an issue with the LICENSE file.
You see you left the original creator [Patbox's](https://github.com/Patbox) name in the license file.
And are blatantly stealing all of their hard work that they made open source, and selling it, without giving them any credit at all. And didn't even bother to remove his name completely.
Not to mention the amount of stolen Minecraft assets in the game y'all didn't bother to change.
So uhh, might wanna get to work on that sweetheart.
Or do something original,
cheers </3

**Comment by levlups** [comment]
rectified the issue  ill add a special thanks file

**Comment by spaceclouds42** [comment]
This does not fix the license violation. Patbox's license states that `The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software,` however this repo, (which qualifies as a copy or substantial portion of Patbox's Software), does not include Patbox's copyright notice.

**Comment by levlups** [comment]
to be honest with you I dont know nothing about licenses and so forth .... How would I fix that !

**Comment by Patbox** [comment]
There is however bigger issue than my code...

You mod includes assets from [PixelPerfection](https://github.com/Athemis/PixelPerfectionCE) resource pack, which is licensed with https://creativecommons.org/licenses/by-sa/4.0/deed.en and I can't see any attribution for it.

Other issue is usage of Minecraft assets, which are copyrighted and you are distributing (and selling) them with this game.

**Comment by Genau6502** [comment]
The license now says the copyright is yours. That's a blatant lie

**Comment by Patbox** [comment]
Yep, I missed that. You can't remove original copyright owner without their approval. You can add yourself to it as another (as you added your own code, but not remove previous)

**Comment by levlups** [comment]
Patbox I will fix all that , do I get your permission to monetize the game , Ill ask Noa Engine also , I'm waiting for your answer, a project needs fund to be great , your a programmer like me , you know that programming alone , leads to knowhere ...

**Comment by Genau6502** [comment]
Fix the license, you don't need permission as long as you comply

**Comment by levlups** [comment]
Ok I'll work on that

**Comment by Genau6502** [comment]
It's not "I'll work on that", it's don't take other people's stuff and remove credit

**Comment by levlups** [comment]
Give me the steps to fix that , I readded patbox license and added his info in the Readme , give me concrete steps

**Comment by Genau6502** [comment]
You haven’t added the correct license back

**Comment by Genau6502** [comment]
This isn’t closed, you haven’t fixed the issue. @Patbox
